### ISSUE TITLE
no websocket with: lc-serve deploy local skyagi-api

### ISSUE THREAD

**Issue by j2l** [litanlitudan/skyagi#183]
Hello, I'm trying hard to make it work locally :)
HTTP seems to work:
```
──────────────────────────────────── 🎉 Flow is ready to serve! ────────────────────────────────────
╭────────────── 🔗 Endpoint ───────────────╮
│  ⛓      Protocol                   HTTP  │
│  🏠        Local           0.0.0.0:8080  │
│  🔒      Private     192.168.1.230:8080  │
│  🌍       Public       86.214.9.96:8080  │
╰──────────────────────────────────────────╯
╭─────────── 💎 HTTP extension ────────────╮
│  💬          Swagger UI        .../docs  │
│  📚               Redoc       .../redoc  │
╰──────────────────────────────────────────╯
Do you love open source? Help us improve Jina in just 1 minute and 30 seconds by taking our survey: 
https://10sw1tcpld4.typeform.com/jinasurveyfeb23?utm_source=jina(Set environment variable 
JINA_HIDE_SURVEY=1 to hide this message.)
```
But the client fail to connect:
```
python skyagi-api-client.py -f ../../examples/BigBangTheory/
Traceback (most recent call last):
  File "/home/pm/skyagi/skyagi/skyagi/skyagi-api/example/skyagi-api-client.py", line 88, in <module>
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/pm/skyagi/skyagi/skyagi/skyagi-api/example/skyagi-api-client.py", line 52, in client
    async with session.ws_connect(f"{url}/{name}") as ws:
  File "/home/pm/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/pm/.local/lib/python3.10/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('ws://localhost:8080/runskyagi')
```
Indeed, I tried the websocket locally and get a 403 (forbidden)

Maybe I missed a step?

**Comment by qizheng7** [comment]
@j2l 
hmm....my client can connect to the server...
```
(venv-skyai-release) qiz@docker-desktop:~/skyagi/skyagi-api/example$ python skyagi-api-client.py -f ../../examples/BigBangTheory/
Connected to ws://localhost:8080/runskyagi.
```
can you try to visit `http://localhost:8080/docs` in your browser? Want to know if the lc server is actually up or not.

Also status 403 means your client doesn't have the authorization to access the API. Is it something regarding your network setting?

**Comment by j2l** [comment]
Thank you @qizheng7 
Sure, here's the result:
![image](https://github.com/litanlitudan/skyagi/assets/65325/e508e130-21af-4f5c-8738-e310bc7da794)
And http://0.0.0.0:8080/healthz returns `status: "ok"`

AFAIK, Ubuntu doesn't block websocket.

To help debug, is there any log with the server?

**Comment by j2l** [comment]
any news?
